export type MaterialSymbolTypes =
  | "account_circle"
  | "add_box"
  | "add_photo_image"
  | "arrow_back"
  | "arrow_forward"
  | "attach_money"
  | "chat"
  | "chevron_left"
  | "chevron_right"
  | "distance"
  | "home"
  | "location_on"
  | "open_in_new"
  | "search"
  | "send"
  | "share"
  | "trash";
